# Generated by Django 4.1.4 on 2022-12-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PyBlog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('update_dt', models.DateTimeField(auto_now=True)),
                ('regist_dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
