# Generated by Django 3.2.16 on 2022-12-11 20:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_pyblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyblog',
            name='regist_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pyblog',
            name='update_dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
